### ISSUE TITLE
Knearest() function Not Working in opencv 3.10

### ISSUE THREAD

**Issue by ghost** [zzh1996/ustc-grade-automatic-notification#15]
When I call 
LINE 23 knn=cv2.KNearest()
in newknn.py
I got an error saying
 'module' object has no attribute 'KNearest'

This version works:
 23  self.knn = cv2.ml.KNearest_create()
 24  self.knn.train(train, cv2.ml.ROW_SAMPLE,label)

**Comment by zzh1996** [comment]
FAQ 里面有写：https://github.com/zzh1996/ustc-grade-automatic-notification/wiki/FAQ
